name: Run unit tests

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
  workflow_dispatch:
  schedule:
    # Run every Tuesday at 03:53 UTC
    - cron: 53 3 * * 2

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-test-pytestoldest
          - os: windows-latest
            python-version: 3.8
            toxenv: py38-test-60
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: py39-test-pytest61
          - os: ubuntu-latest
            python-version: '3.10'
            toxenv: py310-test-pytest71
          - os: macos-latest
            python-version: '3.11'
            toxenv: py311-test-pytest72
          - os: ubuntu-latest
            python-version: '3.11'
            toxenv: py311-test-pytest73
          - os: windows-latest
            python-version: '3.11'
            toxenv: py311-test-pytest74
          - os: ubuntu-latest
            python-version: '3.12'
            toxenv: py312-test-pytest81
          - os: ubuntu-latest
            python-version: '3.12'
            toxenv: py312-test-pytest82
          - os: ubuntu-latest
            python-version: '3.13'
            toxenv: py313-test-pytest83
          - os: macos-latest
            python-version: '3.12'
            toxenv: py312-test-pytestdev
          - os: windows-latest
            python-version: '3.13'
            toxenv: py313-test-pytestdev
          - os: ubuntu-latest
            python-version: '3.13'
            toxenv: py313-test-pytestdev

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox
      run: python -m pip install tox
    - name: Run Tox
      run: tox -v -e ${{ matrix.toxenv }}
